var annotated_dup =
[
    [ "AspNetCore", "namespace_asp_net_core.html", [
      [ "Views__ViewImports", "class_asp_net_core_1_1_views_____view_imports.html", null ],
      [ "Views__ViewStart", "class_asp_net_core_1_1_views_____view_start.html", null ],
      [ "Views_Account_Login", "class_asp_net_core_1_1_views___account___login.html", null ],
      [ "Views_Account_ParentPersonalAccount", "class_asp_net_core_1_1_views___account___parent_personal_account.html", null ],
      [ "Views_Account_PersonalAccount", "class_asp_net_core_1_1_views___account___personal_account.html", null ],
      [ "Views_Account_SchoolWorkerPersonalAccount", "class_asp_net_core_1_1_views___account___school_worker_personal_account.html", null ],
      [ "Views_Account_StudentPersonalAccount", "class_asp_net_core_1_1_views___account___student_personal_account.html", null ],
      [ "Views_Home_About", "class_asp_net_core_1_1_views___home___about.html", null ],
      [ "Views_Home_Contact", "class_asp_net_core_1_1_views___home___contact.html", null ],
      [ "Views_Home_Index", "class_asp_net_core_1_1_views___home___index.html", null ],
      [ "Views_Home_Privacy", "class_asp_net_core_1_1_views___home___privacy.html", null ],
      [ "Views_Journal_GetJournalsStudent", "class_asp_net_core_1_1_views___journal___get_journals_student.html", null ],
      [ "Views_Journal_GetJournalTeacher", "class_asp_net_core_1_1_views___journal___get_journal_teacher.html", null ],
      [ "Views_Parent_ParentPublicAccount", "class_asp_net_core_1_1_views___parent___parent_public_account.html", null ],
      [ "Views_Schedule_GetScheduleSchoolClass", "class_asp_net_core_1_1_views___schedule___get_schedule_school_class.html", null ],
      [ "Views_Schedule_GetScheduleSchoolWorker", "class_asp_net_core_1_1_views___schedule___get_schedule_school_worker.html", null ],
      [ "Views_Schedule_SchedulesListStudent", "class_asp_net_core_1_1_views___schedule___schedules_list_student.html", null ],
      [ "Views_School_GetSchoolById", "class_asp_net_core_1_1_views___school___get_school_by_id.html", null ],
      [ "Views_School_GetSchoolSchoolWorker", "class_asp_net_core_1_1_views___school___get_school_school_worker.html", null ],
      [ "Views_School_GetSchoolsStudent", "class_asp_net_core_1_1_views___school___get_schools_student.html", null ],
      [ "Views_SchoolClass_SchoolClass", "class_asp_net_core_1_1_views___school_class___school_class.html", null ],
      [ "Views_SchoolClass_SchoolClassesList", "class_asp_net_core_1_1_views___school_class___school_classes_list.html", null ],
      [ "Views_SchoolWorker_SchoolWorkerPublicAccount", "class_asp_net_core_1_1_views___school_worker___school_worker_public_account.html", null ],
      [ "Views_SchoolWorker_SchoolWorkersList", "class_asp_net_core_1_1_views___school_worker___school_workers_list.html", null ],
      [ "Views_Shared__CookieConsentPartial", "class_asp_net_core_1_1_views___shared_____cookie_consent_partial.html", null ],
      [ "Views_Shared__Layout", "class_asp_net_core_1_1_views___shared_____layout.html", null ],
      [ "Views_Shared__SchoolCard", "class_asp_net_core_1_1_views___shared_____school_card.html", null ],
      [ "Views_Shared__SchoolCardAdvanced", "class_asp_net_core_1_1_views___shared_____school_card_advanced.html", null ],
      [ "Views_Shared__SchoolClassCard", "class_asp_net_core_1_1_views___shared_____school_class_card.html", null ],
      [ "Views_Shared__SchoolClassCardAdvanced", "class_asp_net_core_1_1_views___shared_____school_class_card_advanced.html", null ],
      [ "Views_Shared__StudentCard", "class_asp_net_core_1_1_views___shared_____student_card.html", null ],
      [ "Views_Shared__StudentCardAdvanced", "class_asp_net_core_1_1_views___shared_____student_card_advanced.html", null ],
      [ "Views_Shared__SubjectCard", "class_asp_net_core_1_1_views___shared_____subject_card.html", null ],
      [ "Views_Shared__ValidationScriptsPartial", "class_asp_net_core_1_1_views___shared_____validation_scripts_partial.html", null ],
      [ "Views_Shared_Error", "class_asp_net_core_1_1_views___shared___error.html", null ],
      [ "Views_Student_GetStudents", "class_asp_net_core_1_1_views___student___get_students.html", null ],
      [ "Views_Student_StudentPublicAccount", "class_asp_net_core_1_1_views___student___student_public_account.html", null ],
      [ "Views_Subject_GetSubject", "class_asp_net_core_1_1_views___subject___get_subject.html", null ],
      [ "Views_Subject_GetSubjectsList", "class_asp_net_core_1_1_views___subject___get_subjects_list.html", null ]
    ] ],
    [ "WebDiary", "namespace_web_diary.html", [
      [ "Controllers", "namespace_web_diary_1_1_controllers.html", [
        [ "AccountController", "class_web_diary_1_1_controllers_1_1_account_controller.html", null ],
        [ "HomeController", "class_web_diary_1_1_controllers_1_1_home_controller.html", null ],
        [ "JournalController", "class_web_diary_1_1_controllers_1_1_journal_controller.html", null ],
        [ "ParentController", "class_web_diary_1_1_controllers_1_1_parent_controller.html", null ],
        [ "ScheduleController", "class_web_diary_1_1_controllers_1_1_schedule_controller.html", null ],
        [ "SchoolClassController", "class_web_diary_1_1_controllers_1_1_school_class_controller.html", null ],
        [ "SchoolController", "class_web_diary_1_1_controllers_1_1_school_controller.html", null ],
        [ "SchoolWorkerController", "class_web_diary_1_1_controllers_1_1_school_worker_controller.html", null ],
        [ "StudentController", "class_web_diary_1_1_controllers_1_1_student_controller.html", null ],
        [ "SubjectController", "class_web_diary_1_1_controllers_1_1_subject_controller.html", null ]
      ] ],
      [ "Data", "namespace_web_diary_1_1_data.html", [
        [ "EFContext", "namespace_web_diary_1_1_data_1_1_e_f_context.html", [
          [ "DbRole", "class_web_diary_1_1_data_1_1_e_f_context_1_1_db_role.html", null ],
          [ "DbUser", "class_web_diary_1_1_data_1_1_e_f_context_1_1_db_user.html", null ],
          [ "DbUserRole", "class_web_diary_1_1_data_1_1_e_f_context_1_1_db_user_role.html", null ],
          [ "EFDbContext", "class_web_diary_1_1_data_1_1_e_f_context_1_1_e_f_db_context.html", null ],
          [ "SeederDB", "class_web_diary_1_1_data_1_1_e_f_context_1_1_seeder_d_b.html", null ]
        ] ],
        [ "Interfaces", "namespace_web_diary_1_1_data_1_1_interfaces.html", [
          [ "IJournal", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_journal.html", null ],
          [ "ILesson", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_lesson.html", null ],
          [ "IMark", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_mark.html", null ],
          [ "IParent", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_parent.html", null ],
          [ "IPerson", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_person.html", null ],
          [ "ISchedule", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_schedule.html", null ],
          [ "ISchool", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_school.html", null ],
          [ "ISchoolClass", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_school_class.html", null ],
          [ "ISchoolWorker", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_school_worker.html", null ],
          [ "IStudent", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_student.html", null ],
          [ "ISubject", "interface_web_diary_1_1_data_1_1_interfaces_1_1_i_subject.html", null ]
        ] ],
        [ "Models", "namespace_web_diary_1_1_data_1_1_models.html", [
          [ "Journal", "class_web_diary_1_1_data_1_1_models_1_1_journal.html", null ],
          [ "Lesson", "class_web_diary_1_1_data_1_1_models_1_1_lesson.html", null ],
          [ "LessonInfo", "class_web_diary_1_1_data_1_1_models_1_1_lesson_info.html", null ],
          [ "Mark", "class_web_diary_1_1_data_1_1_models_1_1_mark.html", null ],
          [ "Parent", "class_web_diary_1_1_data_1_1_models_1_1_parent.html", null ],
          [ "Person", "class_web_diary_1_1_data_1_1_models_1_1_person.html", null ],
          [ "Schedule", "class_web_diary_1_1_data_1_1_models_1_1_schedule.html", null ],
          [ "School", "class_web_diary_1_1_data_1_1_models_1_1_school.html", null ],
          [ "SchoolClass", "class_web_diary_1_1_data_1_1_models_1_1_school_class.html", null ],
          [ "SchoolClassStudent", "class_web_diary_1_1_data_1_1_models_1_1_school_class_student.html", null ],
          [ "SchoolStudent", "class_web_diary_1_1_data_1_1_models_1_1_school_student.html", null ],
          [ "SchoolWorker", "class_web_diary_1_1_data_1_1_models_1_1_school_worker.html", null ],
          [ "Student", "class_web_diary_1_1_data_1_1_models_1_1_student.html", null ],
          [ "StudentSubject", "class_web_diary_1_1_data_1_1_models_1_1_student_subject.html", null ],
          [ "Subject", "class_web_diary_1_1_data_1_1_models_1_1_subject.html", null ],
          [ "UserProfile", "class_web_diary_1_1_data_1_1_models_1_1_user_profile.html", null ]
        ] ],
        [ "Repository", "namespace_web_diary_1_1_data_1_1_repository.html", [
          [ "JournalRepository", "class_web_diary_1_1_data_1_1_repository_1_1_journal_repository.html", null ],
          [ "ParentRepository", "class_web_diary_1_1_data_1_1_repository_1_1_parent_repository.html", null ],
          [ "ScheduleRepository", "class_web_diary_1_1_data_1_1_repository_1_1_schedule_repository.html", null ],
          [ "SchoolClassRepository", "class_web_diary_1_1_data_1_1_repository_1_1_school_class_repository.html", null ],
          [ "SchoolRepository", "class_web_diary_1_1_data_1_1_repository_1_1_school_repository.html", null ],
          [ "SchoolWorkerRepository", "class_web_diary_1_1_data_1_1_repository_1_1_school_worker_repository.html", null ],
          [ "StudentRepository", "class_web_diary_1_1_data_1_1_repository_1_1_student_repository.html", null ],
          [ "SubjectRepository", "class_web_diary_1_1_data_1_1_repository_1_1_subject_repository.html", null ]
        ] ],
        [ "ViewModels", "namespace_web_diary_1_1_data_1_1_view_models.html", [
          [ "JournalViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_journal_view_model.html", null ],
          [ "ListJournalsStudentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_journals_student_view_model.html", null ],
          [ "ListJournalViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_journal_view_model.html", null ],
          [ "ListParentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_parent_view_model.html", null ],
          [ "ListScheduleStudentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_schedule_student_view_model.html", null ],
          [ "ListScheduleViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_schedule_view_model.html", null ],
          [ "ListSchoolClassViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_school_class_view_model.html", null ],
          [ "ListSchoolViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_school_view_model.html", null ],
          [ "ListSchoolWorkerViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_school_worker_view_model.html", null ],
          [ "ListStudentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_student_view_model.html", null ],
          [ "ListSubjectViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_list_subject_view_model.html", null ],
          [ "LoginViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_login_view_model.html", null ],
          [ "ParentPersonalAccountViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_parent_personal_account_view_model.html", null ],
          [ "ParentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_parent_view_model.html", null ],
          [ "PersonalAccountViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_personal_account_view_model.html", null ],
          [ "ScheduleStudentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_schedule_student_view_model.html", null ],
          [ "ScheduleTeacherViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_schedule_teacher_view_model.html", null ],
          [ "ScheduleViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_schedule_view_model.html", null ],
          [ "SchoolClassViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_school_class_view_model.html", null ],
          [ "SchoolViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_school_view_model.html", null ],
          [ "SchoolWorkerPersonalAccountViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_school_worker_personal_account_view_model.html", null ],
          [ "SchoolWorkerViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_school_worker_view_model.html", null ],
          [ "StudentPersonalAccountViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_student_personal_account_view_model.html", null ],
          [ "StudentViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_student_view_model.html", null ],
          [ "SubjectViewModel", "class_web_diary_1_1_data_1_1_view_models_1_1_subject_view_model.html", null ]
        ] ]
      ] ],
      [ "Migrations", "namespace_web_diary_1_1_migrations.html", [
        [ "EFDbContextModelSnapshot", "class_web_diary_1_1_migrations_1_1_e_f_db_context_model_snapshot.html", null ],
        [ "fixsc", "class_web_diary_1_1_migrations_1_1fixsc.html", null ]
      ] ],
      [ "Models", "namespace_web_diary_1_1_models.html", [
        [ "ErrorViewModel", "class_web_diary_1_1_models_1_1_error_view_model.html", null ],
        [ "UserInfo", "class_web_diary_1_1_models_1_1_user_info.html", null ]
      ] ],
      [ "Program", "class_web_diary_1_1_program.html", null ],
      [ "Startup", "class_web_diary_1_1_startup.html", null ]
    ] ]
];