var dir_23980e094dc8b2bbea28b419710899ad =
[
    [ "JournalViewModel.cs", "_journal_view_model_8cs.html", "_journal_view_model_8cs" ],
    [ "ListJournalsStudentViewModel.cs", "_list_journals_student_view_model_8cs.html", "_list_journals_student_view_model_8cs" ],
    [ "ListJournalViewModel.cs", "_list_journal_view_model_8cs.html", "_list_journal_view_model_8cs" ],
    [ "ListParentViewModel.cs", "_list_parent_view_model_8cs.html", "_list_parent_view_model_8cs" ],
    [ "ListScheduleStudentViewModel.cs", "_list_schedule_student_view_model_8cs.html", "_list_schedule_student_view_model_8cs" ],
    [ "ListScheduleViewModel.cs", "_list_schedule_view_model_8cs.html", "_list_schedule_view_model_8cs" ],
    [ "ListSchoolClassViewModel.cs", "_list_school_class_view_model_8cs.html", "_list_school_class_view_model_8cs" ],
    [ "ListSchoolViewModel.cs", "_list_school_view_model_8cs.html", "_list_school_view_model_8cs" ],
    [ "ListSchoolWorkerViewModel.cs", "_list_school_worker_view_model_8cs.html", "_list_school_worker_view_model_8cs" ],
    [ "ListStudentViewModel.cs", "_list_student_view_model_8cs.html", "_list_student_view_model_8cs" ],
    [ "ListSubjectViewModel.cs", "_list_subject_view_model_8cs.html", "_list_subject_view_model_8cs" ],
    [ "LoginViewModel.cs", "_login_view_model_8cs.html", "_login_view_model_8cs" ],
    [ "ParentPersonalAccountViewModel.cs", "_parent_personal_account_view_model_8cs.html", "_parent_personal_account_view_model_8cs" ],
    [ "ParentViewModel.cs", "_parent_view_model_8cs.html", "_parent_view_model_8cs" ],
    [ "PersonalAccountViewModel.cs", "_personal_account_view_model_8cs.html", "_personal_account_view_model_8cs" ],
    [ "ScheduleStudentViewModel.cs", "_schedule_student_view_model_8cs.html", "_schedule_student_view_model_8cs" ],
    [ "ScheduleTeacherViewModel.cs", "_schedule_teacher_view_model_8cs.html", "_schedule_teacher_view_model_8cs" ],
    [ "ScheduleViewModel.cs", "_schedule_view_model_8cs.html", "_schedule_view_model_8cs" ],
    [ "SchoolClassViewModel.cs", "_school_class_view_model_8cs.html", "_school_class_view_model_8cs" ],
    [ "SchoolViewModel.cs", "_school_view_model_8cs.html", "_school_view_model_8cs" ],
    [ "SchoolWorkerPersonalAccountViewModel.cs", "_school_worker_personal_account_view_model_8cs.html", "_school_worker_personal_account_view_model_8cs" ],
    [ "SchoolWorkerViewModel.cs", "_school_worker_view_model_8cs.html", "_school_worker_view_model_8cs" ],
    [ "StudentPersonalAccountViewModel.cs", "_student_personal_account_view_model_8cs.html", "_student_personal_account_view_model_8cs" ],
    [ "StudentViewModel.cs", "_student_view_model_8cs.html", "_student_view_model_8cs" ],
    [ "SubjectViewModel.cs", "_subject_view_model_8cs.html", "_subject_view_model_8cs" ]
];