var searchData=
[
  ['v0_0',['Migration from Popper.js v0',['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/popper.js/README.md#autotoc_md43',1,'']]],
  ['value_1',['Value',['../class_web_diary_1_1_data_1_1_models_1_1_mark.html#ac12eb20c000a211b717542086c78b052',1,'WebDiary::Data::Models::Mark']]],
  ['versioning_2',['Versioning',['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/bootstrap/README.md#autotoc_md10',1,'Versioning'],['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/font-awesome/README.md#autotoc_md21',1,'Versioning']]],
  ['views_5f_5fviewimports_3',['Views__ViewImports',['../class_asp_net_core_1_1_views_____view_imports.html',1,'AspNetCore']]],
  ['views_5f_5fviewstart_4',['Views__ViewStart',['../class_asp_net_core_1_1_views_____view_start.html',1,'AspNetCore']]],
  ['views_5faccount_5flogin_5',['Views_Account_Login',['../class_asp_net_core_1_1_views___account___login.html',1,'AspNetCore']]],
  ['views_5faccount_5fparentpersonalaccount_6',['Views_Account_ParentPersonalAccount',['../class_asp_net_core_1_1_views___account___parent_personal_account.html',1,'AspNetCore']]],
  ['views_5faccount_5fpersonalaccount_7',['Views_Account_PersonalAccount',['../class_asp_net_core_1_1_views___account___personal_account.html',1,'AspNetCore']]],
  ['views_5faccount_5fschoolworkerpersonalaccount_8',['Views_Account_SchoolWorkerPersonalAccount',['../class_asp_net_core_1_1_views___account___school_worker_personal_account.html',1,'AspNetCore']]],
  ['views_5faccount_5fstudentpersonalaccount_9',['Views_Account_StudentPersonalAccount',['../class_asp_net_core_1_1_views___account___student_personal_account.html',1,'AspNetCore']]],
  ['views_5fhome_5fabout_10',['Views_Home_About',['../class_asp_net_core_1_1_views___home___about.html',1,'AspNetCore']]],
  ['views_5fhome_5fcontact_11',['Views_Home_Contact',['../class_asp_net_core_1_1_views___home___contact.html',1,'AspNetCore']]],
  ['views_5fhome_5findex_12',['Views_Home_Index',['../class_asp_net_core_1_1_views___home___index.html',1,'AspNetCore']]],
  ['views_5fhome_5fprivacy_13',['Views_Home_Privacy',['../class_asp_net_core_1_1_views___home___privacy.html',1,'AspNetCore']]],
  ['views_5fjournal_5fgetjournalsstudent_14',['Views_Journal_GetJournalsStudent',['../class_asp_net_core_1_1_views___journal___get_journals_student.html',1,'AspNetCore']]],
  ['views_5fjournal_5fgetjournalteacher_15',['Views_Journal_GetJournalTeacher',['../class_asp_net_core_1_1_views___journal___get_journal_teacher.html',1,'AspNetCore']]],
  ['views_5fparent_5fparentpublicaccount_16',['Views_Parent_ParentPublicAccount',['../class_asp_net_core_1_1_views___parent___parent_public_account.html',1,'AspNetCore']]],
  ['views_5fschedule_5fgetscheduleschoolclass_17',['Views_Schedule_GetScheduleSchoolClass',['../class_asp_net_core_1_1_views___schedule___get_schedule_school_class.html',1,'AspNetCore']]],
  ['views_5fschedule_5fgetscheduleschoolworker_18',['Views_Schedule_GetScheduleSchoolWorker',['../class_asp_net_core_1_1_views___schedule___get_schedule_school_worker.html',1,'AspNetCore']]],
  ['views_5fschedule_5fschedulesliststudent_19',['Views_Schedule_SchedulesListStudent',['../class_asp_net_core_1_1_views___schedule___schedules_list_student.html',1,'AspNetCore']]],
  ['views_5fschool_5fgetschoolbyid_20',['Views_School_GetSchoolById',['../class_asp_net_core_1_1_views___school___get_school_by_id.html',1,'AspNetCore']]],
  ['views_5fschool_5fgetschoolschoolworker_21',['Views_School_GetSchoolSchoolWorker',['../class_asp_net_core_1_1_views___school___get_school_school_worker.html',1,'AspNetCore']]],
  ['views_5fschool_5fgetschoolsstudent_22',['Views_School_GetSchoolsStudent',['../class_asp_net_core_1_1_views___school___get_schools_student.html',1,'AspNetCore']]],
  ['views_5fschoolclass_5fschoolclass_23',['Views_SchoolClass_SchoolClass',['../class_asp_net_core_1_1_views___school_class___school_class.html',1,'AspNetCore']]],
  ['views_5fschoolclass_5fschoolclasseslist_24',['Views_SchoolClass_SchoolClassesList',['../class_asp_net_core_1_1_views___school_class___school_classes_list.html',1,'AspNetCore']]],
  ['views_5fschoolworker_5fschoolworkerpublicaccount_25',['Views_SchoolWorker_SchoolWorkerPublicAccount',['../class_asp_net_core_1_1_views___school_worker___school_worker_public_account.html',1,'AspNetCore']]],
  ['views_5fschoolworker_5fschoolworkerslist_26',['Views_SchoolWorker_SchoolWorkersList',['../class_asp_net_core_1_1_views___school_worker___school_workers_list.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fcookieconsentpartial_27',['Views_Shared__CookieConsentPartial',['../class_asp_net_core_1_1_views___shared_____cookie_consent_partial.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5flayout_28',['Views_Shared__Layout',['../class_asp_net_core_1_1_views___shared_____layout.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fschoolcard_29',['Views_Shared__SchoolCard',['../class_asp_net_core_1_1_views___shared_____school_card.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fschoolcardadvanced_30',['Views_Shared__SchoolCardAdvanced',['../class_asp_net_core_1_1_views___shared_____school_card_advanced.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fschoolclasscard_31',['Views_Shared__SchoolClassCard',['../class_asp_net_core_1_1_views___shared_____school_class_card.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fschoolclasscardadvanced_32',['Views_Shared__SchoolClassCardAdvanced',['../class_asp_net_core_1_1_views___shared_____school_class_card_advanced.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fstudentcard_33',['Views_Shared__StudentCard',['../class_asp_net_core_1_1_views___shared_____student_card.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fstudentcardadvanced_34',['Views_Shared__StudentCardAdvanced',['../class_asp_net_core_1_1_views___shared_____student_card_advanced.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fsubjectcard_35',['Views_Shared__SubjectCard',['../class_asp_net_core_1_1_views___shared_____subject_card.html',1,'AspNetCore']]],
  ['views_5fshared_5f_5fvalidationscriptspartial_36',['Views_Shared__ValidationScriptsPartial',['../class_asp_net_core_1_1_views___shared_____validation_scripts_partial.html',1,'AspNetCore']]],
  ['views_5fshared_5ferror_37',['Views_Shared_Error',['../class_asp_net_core_1_1_views___shared___error.html',1,'AspNetCore']]],
  ['views_5fstudent_5fgetstudents_38',['Views_Student_GetStudents',['../class_asp_net_core_1_1_views___student___get_students.html',1,'AspNetCore']]],
  ['views_5fstudent_5fstudentpublicaccount_39',['Views_Student_StudentPublicAccount',['../class_asp_net_core_1_1_views___student___student_public_account.html',1,'AspNetCore']]],
  ['views_5fsubject_5fgetsubject_40',['Views_Subject_GetSubject',['../class_asp_net_core_1_1_views___subject___get_subject.html',1,'AspNetCore']]],
  ['views_5fsubject_5fgetsubjectslist_41',['Views_Subject_GetSubjectsList',['../class_asp_net_core_1_1_views___subject___get_subjects_list.html',1,'AspNetCore']]],
  ['vs_20production_20mode_42',['Development vs. Production Mode',['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/vue/dist/README.md#autotoc_md62',1,'']]],
  ['vs_20runtime_20only_43',['Runtime + Compiler vs. Runtime-only',['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/vue/dist/README.md#autotoc_md58',1,'']]],
  ['vue_20js_20angular_20angularjs_20ember_20js_20etc_20integration_44',['React, Vue.js, Angular, AngularJS, Ember.js (etc...) integration',['../C:/Users/Markian/Documents/programming/Web Diary/Web Diary/WebDiary/WebDiary/node_modules/popper.js/README.md#autotoc_md42',1,'']]]
];
